### ISSUE TITLE
With this parameters, the channel would add or remove energy.

### ISSUE THREAD

**Issue by lhao-sudo** [veeresht/CommPy#126]
Traceback (most recent call last):
  File "C:/Users/lihao/Desktop/ofdm_v1.py", line 169, in <module>
    OFDM_simulation()
  File "C:/Users/lihao/Desktop/ofdm_v1.py", line 136, in OFDM_simulation
    OFDM_RX = channel(OFDM_TX, SNRdb, "tdl")
  File "C:/Users/lihao/Desktop/ofdm_v1.py", line 81, in channel
    channel = SISOFlatChannel(None,(1+0j,1+0j))
  File "C:\Users\lihao\AppData\Local\Programs\Python\Python310\lib\site-packages\commpy\channels.py", line 179, in __init__
    self.fading_param = fading_param
  File "C:\Users\lihao\AppData\Local\Programs\Python\Python310\lib\site-packages\commpy\channels.py", line 231, in fading_param
    raise ValueError("With this parameters, the channel would add or remove energy.")
ValueError: With this parameters, the channel would add or remove energy.

**Comment by BastienTr** [comment]
Sorry for the long delay. This package is no more actively monitored since I have a new job. If you still need help, please reopen the issue and provide the code that lead to this error. I'd have a look
